### ISSUE TITLE
Cannot read property 'logger' of undefined error

### ISSUE THREAD

**Issue by kiequoo** [jivesoftware/hubot-jira-lookup#26]
Hi there, recent versions of the script have started crashing for us when doing a lookup, here's the stack trace from the log:

```
2015-12-31T07:30:34.165082+00:00 app[web.1]: [Thu Dec 31 2015 07:30:34 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'logger' of undefined
2015-12-31T07:30:34.165087+00:00 app[web.1]:   at reportIssue (/app/node_modules/hubot-jira-lookup/scripts/jira-lookup.coffee:115:24, <js>:118:15)
2015-12-31T07:30:34.165088+00:00 app[web.1]:   at TextListener.callback (/app/node_modules/hubot-jira-lookup/scripts/jira-lookup.coffee:109:5, <js>:109:23)
2015-12-31T07:30:34.165089+00:00 app[web.1]:   at executeListener (/app/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
2015-12-31T07:30:34.165089+00:00 app[web.1]:   at allDone (/app/node_modules/hubot/src/middleware.coffee:41:37, <js>:32:16)
2015-12-31T07:30:34.165090+00:00 app[web.1]:   at /app/node_modules/async/lib/async.js:274:13
2015-12-31T07:30:34.165091+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/async/lib/async.js:142:20)
2015-12-31T07:30:34.165091+00:00 app[web.1]:   at Object.async.reduce (/app/node_modules/async/lib/async.js:268:15)
2015-12-31T07:30:34.165092+00:00 app[web.1]:   at /app/node_modules/hubot/src/middleware.coffee:46:7, <js>:35:22
2015-12-31T07:30:34.165093+00:00 app[web.1]:   at doNTCallback0 (node.js:430:9)
2015-12-31T07:30:34.165093+00:00 app[web.1]:   at process._tickCallback (node.js:359:13)
2015-12-31T07:30:34.165094+00:00 app[web.1]:
2015-12-31T07:30:35.085806+00:00 heroku[web.1]: Process exited with status 0
```

Any ideas?

**Comment by aaronware** [comment]
@kiequoo I submitted a pull request to fix the invalid reference. But if you are feeling handy you can always make a quick update to your local file as seen in https://github.com/jivesoftware/hubot-jira-lookup/pull/27

**Comment by kiequoo** [comment]
Thanks!  Will fix it locally as the pull request seems to be taking a while to be merged :)

**Comment by themartorana** [comment]
@aaronware thanks for this!

**Comment by aaronware** [comment]
@themartorana No problem. Glad it helped you out

**Comment by rarrarrarr** [comment]
This helped me, also.  Here's my +1 for getting this PR merged!

**Comment by sethp-jive** [comment]
Sorry for the delay in getting this merged, but big thanks to @aaronware for the help!
